// PROFILE
export const POST_ADD = 'POST_ADD'
export const PROFILE_SET_USER_PROFILE = 'PROFILE_SET_USER_PROFILE'
export const PROFILE_GET_STATUS = 'PROFILE_GET_STATUS'

// DIALOGS
export const MESSAGES_ADD = 'MESSAGES_ADD'

// USERS
export const USERS_FOLLOW = 'USERS_FOLLOW'
export const USERS_UNFOLLOW = 'USERS_UNFOLLOW'
export const USERS_SET = 'USERS_SET'
export const USERS_SET_CURRENT_PAGE = 'USERS_SET_CURRENT_PAGE'
export const USERS_SET_TOTAL_COUNT = 'USERS_SET_TOTAL_COUNT'
export const USERS_IS_LOADING = 'USERS_IS_LOADING'
export const USERS_FOLLOWING_IN_PROGRESS = 'USERS_FOLLOWING_IN_PROGRESS'

// AUTH
export const AUTH_SET_USER_DATA = 'AUTH_SET_USER_DATA'