// PROFILE
export const POST_ADD = 'POST_ADD'
export const POST_UPDATE_NEW_TEXT =  'POST_UPDATE_NEW_TEXT'

// DIALOGS
export const MESSAGES_ADD = 'MESSAGES_ADD'
export const MESSAGES_UPDATE_NEW_TEXT =  'MESSAGES_UPDATE_NEW_TEXT'