// APP
export const APP_INITIALIZED = 'APP_INITIALIZED'

// PROFILE
export const PROFILE_POST_ADD = 'PROFILE_POST_ADD'
export const PROFILE_POST_DELETE = 'PROFILE_POST_DELETE'
export const PROFILE_SET_USER_PROFILE = 'PROFILE_SET_USER_PROFILE'
export const PROFILE_GET_STATUS = 'PROFILE_GET_STATUS'
export const PROFILE_PHOTO_SAVE_SUCCESS = 'PROFILE_PHOTO_SAVE_SUCCESS'

// DIALOGS
export const MESSAGES_ADD = 'MESSAGES_ADD'

// USERS
export const USERS_FOLLOW = 'USERS_FOLLOW'
export const USERS_UNFOLLOW = 'USERS_UNFOLLOW'
export const USERS_SET = 'USERS_SET'
export const USERS_SET_CURRENT_PAGE = 'USERS_SET_CURRENT_PAGE'
export const USERS_SET_TOTAL_COUNT = 'USERS_SET_TOTAL_COUNT'
export const USERS_IS_LOADING = 'USERS_IS_LOADING'
export const USERS_FOLLOWING_IN_PROGRESS = 'USERS_FOLLOWING_IN_PROGRESS'
export const USERS_SET_FILTER = 'USERS_SET_FILTER'

// AUTH
export const AUTH_SET_USER_DATA = 'AUTH_SET_USER_DATA'
export const AUTH_GET_CAPTCHA_URL = 'AUTH_GET_CAPTCHA_URL'